In [1]:
from ciftipy.main import CiftiImg, load
import numpy as np
import nibabel as nb

/home/mcespedes/.cache/pypoetry/virtualenvs/ciftipy-w2vl7rWg-py3.10/lib/python3.10/site-packages/thefuzz/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


## dlabel file test

In [5]:
fname = '/home/mcespedes/Documents/code/test-folder/sub-P022_space-T1w_den-0p5mm_label-hipp_atlas-bigbrain_subfields.dlabel.nii'

In [6]:
cifti_file = nb.load(fname)
type(cifti_file)

nibabel.cifti2.cifti2.Cifti2Image

In [7]:
orig_axes = [cifti_file.header.get_axis(i) for i in range(cifti_file.ndim)]

In [8]:
test_image = CiftiImg(cifti_file)

In [9]:
axes = test_image.axis
axes

[[<ciftipy.main.LabelTable object at 0x7f9d51ebb700>
  Label Table
  -----------
      name: #1
      labels: ???, Subiculum, CA1, CA2, CA3, CA4],
 BrainModel: length=14524 {voxels=0, vertices=14524}]

In [10]:
# Get mask from labels in dlabel image
axes[0][0].label['CA1']

array([[False, False, False, ..., False, False, False]])

In [11]:
# Get mask from keys in dlabel image
axes[0][0].key[0]

array([[False, False, False, ..., False, False, False]])

In [12]:
# Test BrainModel
bm_axis = axes[1]

In [13]:
# Mask based on the elements that are vertices
print(orig_axes[1].vertex)
bm_axis.vertices

[   0    1    2 ... 7259 7260 7261]


array([ True,  True,  True, ...,  True,  True,  True])

In [14]:
# Mask based on the elements that are vertices
print(orig_axes[1].voxel)
bm_axis.voxels

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 ...
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


array([False, False, False, ..., False, False, False])

In [15]:
len(bm_axis)

14524

## dscalar

In [2]:
fname = '/home/mcespedes/Documents/code/test-folder/sub-P022_space-T1w_den-0p5mm_label-hipp_curvature.dscalar.nii'

In [3]:
cifti_scalar = nb.load(fname)

In [4]:
orig_axes = [cifti_scalar.header.get_axis(i) for i in range(cifti_scalar.ndim)]

In [5]:
len(orig_axes[0])

1

In [6]:
test_image = CiftiImg(cifti_scalar)

In [7]:
axes = test_image.axis
axes

[ScalarAxis: {name=['mean curvature'], meta=[{}]},
 BrainModel: length=14524 {voxels=0, vertices=14524}]

In [33]:
axes[0].name

array(['mean curvature'], dtype='<U14')

In [10]:
np.array(test_image).shape

(1, 14524)

## dseries

In [7]:
fname = '/home/mcespedes/Documents/code/test-folder/sub-S01_task-rest_dir-AP_run-1_space-fsLR_den-91k_bold.dtseries.nii'

In [8]:
cifti_series = nb.load(fname)

In [9]:
orig_axes = [cifti_series.header.get_axis(i) for i in range(cifti_series.ndim)]

In [10]:
test_image = CiftiImg(cifti_series)

In [11]:
axes = test_image.axis
axes

[Series: {start=0.0, step=2.0, length=300, unit=SECOND},
 BrainModel: length=91282 {voxels=31870, vertices=59412}]

In [7]:
print(axes[0].unit)
print(axes[0].start)
print(axes[0].step)
print(axes[0].length)
print(axes[0].exponent)

SECOND
0.0
2.0
300
0


In [12]:
len(axes[0])

300

In [8]:
a = np.zeros(300).astype(bool)
a[0:10] = True
a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [9]:
caca = test_image[a,2:4]

In [10]:
caca.axis[0].length

10

In [11]:
type(caca)

ciftipy.main.CiftiImg

In [12]:
caca.save('test.dtseries.nii')

In [13]:
test_load = load('test.dtseries.nii')
test_load

CiftiImg
    Dims: {len(self.shape)}
    -------
    BrainModel: length=2 {voxels=0, vertices=2}

In [15]:
test_load.axis[0].size

TypeError: object of type 'SeriesAxis' has no len()