In [12]:
import nibabel as nb
import numpy as np

## dlabel

### Extra

In [4]:
fname = './sub-P022_space-T1w_den-0p5mm_label-hipp_atlas-bigbrain_subfields.dlabel.nii'

In [5]:
cifti_file = nb.load(fname)
type(cifti_file)

nibabel.cifti2.cifti2.Cifti2Image

In [13]:
data = np.array([[1,2,3,4]])
data.shape

(1, 4)

In [15]:
caca = nb.cifti2.Cifti2Image(data, cifti_file.header, cifti_file.nifti_header, cifti_file.extra, cifti_file.file_map)

/home/mcespedes/Documents/code/test-folder/venv/lib/python3.10/site-packages/nibabel/cifti2/cifti2.py:1466: UserWarning: Dataobj shape (1, 4) does not match shape expected from CIFTI-2 header (1, 14524)
  warn(


In [19]:
caca.nifti_header.get_data_shape()

(1, 1, 1, 1, 1, 4)

In [7]:
cifti_file.shape

(1, 14524)

In [6]:
type(cifti_file.header)

nibabel.cifti2.cifti2.Cifti2Header

In [7]:
axes = [cifti_file.header.get_axis(i) for i in range(cifti_file.ndim)]

In [10]:
type(axes[0])

nibabel.cifti2.cifti2_axes.LabelAxis

In [11]:
axes[0].meta # https://nipy.org/nibabel/reference/nibabel.cifti2.html#nibabel.cifti2.cifti2_axes.LabelAxis

array([{}], dtype=object)

### Presentation

In [31]:
# Current implementation

import numpy as np
import nibabel as nb

# Import label
fname = './sub-P022_space-T1w_den-0p5mm_label-hipp_atlas-bigbrain_subfields.dlabel.nii'
cifti_file = nb.load(fname)

# Import image
img = nb.load('./sub-P022_space-T1w_den-0p5mm_label-hipp_curvature.dscalar.nii').get_fdata()

# Get indexes for 1 key
idx = np.where((cifti_file.get_fdata().astype(int)==1)[0])
# index based on these
print(img[:,idx])

# Get index for 1 label
axes = [cifti_file.header.get_axis(i) for i in range(cifti_file.ndim)]
labels = axes[0].label[0]
# Get key associated to label
key_label = list(zip(*labels.values()))[0].index('CA1')
# Get the indexes associated with key
idx = np.where((cifti_file.get_fdata().astype(int)==key_label)[0])
# indexing
print(img[:,idx])

[[[-0.15270406 -0.10130453 -0.10375933 ...  0.7144177   0.58595586
    0.59983456]]]
[[[-0.17896667 -0.12353849 -0.06151204 ...  0.15536353  0.27006435
    0.25702739]]]


In [ ]:
# Our implementation
import ciftipy as cp

# loading label file
fname = './sub-P022_space-T1w_den-0p5mm_label-hipp_atlas-bigbrain_subfields.dlabel.nii'
label_data = cp.load(fname)

# loading img file
img = nb.load('./sub-P022_space-T1w_den-0p5mm_label-hipp_curvature.dscalar.nii')

# indexing based on keys
idx = label_data.keys[1]
print(img[idx, :])

# indexing  based on labels
idx = label_data.labels['CA1']
print(img[idx, :])


## dseries

In [24]:
fname_series = './sub-S01_task-rest_dir-AP_run-1_space-fsLR_den-91k_bold.dtseries.nii'

In [25]:
cifti_series = nb.load(fname_series)
type(cifti_series)

nibabel.cifti2.cifti2.Cifti2Image

In [64]:
cifti_series.shape

(300, 91282)

In [136]:
cifti_series.get_fdata().shape

(300, 91282)

In [27]:
axes = [cifti_series.header.get_axis(i) for i in range(cifti_series.ndim)]
axes

In [144]:
[element for element in axes if isinstance(element, nb.cifti2.cifti2_axes.BrainModelAxis)][0]

In [46]:
axes[0].unit # https://nipy.org/nibabel/reference/nibabel.cifti2.html#nibabel.cifti2.cifti2_axes.SeriesAxis

'SECOND'

In [134]:
list(axes[1].iter_structures())# https://nipy.org/nibabel/reference/nibabel.cifti2.html#nibabel.cifti2.cifti2_axes.BrainModelAxis

[('CIFTI_STRUCTURE_CORTEX_LEFT',
  slice(0, 29696, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f354c037b80>),
 ('CIFTI_STRUCTURE_CORTEX_RIGHT',
  slice(29696, 59412, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f35740f6410>),
 ('CIFTI_STRUCTURE_ACCUMBENS_LEFT',
  slice(59412, 59547, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f35740f75e0>),
 ('CIFTI_STRUCTURE_ACCUMBENS_RIGHT',
  slice(59547, 59687, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f35740f52a0>),
 ('CIFTI_STRUCTURE_AMYGDALA_LEFT',
  slice(59687, 60002, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f35740f45e0>),
 ('CIFTI_STRUCTURE_AMYGDALA_RIGHT',
  slice(60002, 60334, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f35740f7e20>),
 ('CIFTI_STRUCTURE_BRAIN_STEM',
  slice(60334, 63806, None),
  <nibabel.cifti2.cifti2_axes.BrainModelAxis at 0x7f35740f6c80>),
 ('CIFTI_STRUCTURE_CAUDATE_LEFT',
  slice(63806, 64534, None),
  <nibabel.cifti2.cifti2_axes.Bra

In [39]:
axes[1].name.shape

(91282,)

In [130]:
caca = axes[1].voxel[:,0]
print(len(caca)- len(caca[caca!=-1]))

59412


In [132]:
vertexidx = axes[1].vertex
vertexidx = vertexidx[vertexidx!=-1]
len(vertexidx)

59412

In [140]:
vertexidx[vertexidx==0]

array([0, 0])

In [155]:
axes[1].voxel

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       ...,
       [45, 56, 38],
       [45, 56, 40],
       [45, 56, 41]])

In [156]:
a = axes[1].vertex
b = axes[1].voxel[:,0]
len(a[a!=-1]) +len(b[b!=-1])

91282

In [125]:
voxels = axes[1].voxel[:,0]
len(voxels[voxels!=-1])

31870

In [110]:
voxelsid = np.unique(axes[1].voxel[:,0])
voxelsid

array([-1, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72])

In [147]:
axes[1].voxel.shape

(91282, 3)

In [112]:
slice(1,10,2).stop

10

In [113]:
4 in range(2,8)

True

In [72]:
import numpy as np
import nibabel as nb
from nibabel.cifti2 import cifti2
from typing import Any, Mapping, Sequence, SupportsIndex, TypeAlias, TypeVar


class CiftiImg:
    def __init__(self, cifti: cifti2.Cifti2Image):
        self.nibabel_obj = cifti
    
    @property
    def shape(self):
        return self.nibabel_obj.shape

    def __getitem__(self, __index):
        # Get the data
        data = self.nibabel_obj.get_fdata()
        # Index the dataobj
        new_data = data[__index]
        # Update the header

        # Construct a new object
        new_nb_obj =  nb.cifti2.Cifti2Image(new_data, self.nibabel_obj.header,
                                            self.nibabel_obj.nifti_header,
                                            self.nibabel_obj.extra,
                                            self.nibabel_obj.file_map)
        return CiftiImg(new_nb_obj)

In [73]:
caca = CiftiImg(cifti_series)

In [74]:
lolo = caca.__getitem__(slice(0,10))

/home/mcespedes/Documents/code/test-folder/venv/lib/python3.10/site-packages/nibabel/cifti2/cifti2.py:1466: UserWarning: Dataobj shape (10, 91282) does not match shape expected from CIFTI-2 header (300, 91282)
  warn(


In [75]:
lolo.shape

(10, 91282)

## dscalar

In [49]:
fname_scalar = '/home/mcespedes/Documents/Results/hippunfold/sub-P022/surf/sub-P022_space-T1w_den-0p5mm_label-hipp_curvature.dscalar.nii'

In [50]:
cifti_scalar = nb.load(fname_scalar)
type(cifti_scalar)

nibabel.cifti2.cifti2.Cifti2Image

In [51]:
cifti_scalar.get_fdata().shape

(1, 14524)

In [52]:
axes = [cifti_scalar.header.get_axis(i) for i in range(cifti_scalar.ndim)]
axes

In [53]:
axes[0].name # https://nipy.org/nibabel/reference/nibabel.cifti2.html#nibabel.cifti2.cifti2_axes.ScalarAxis

array(['mean curvature'], dtype='<U14')

In [54]:
axes[0].meta

array([{}], dtype=object)